"""Claude Code and Codex sessions: what sync keeps, reading only what's new, and the messages index builds."""
import hashlib
import json
import os
import sqlite3

import pytest


@pytest.fixture
def home(tmp_path, monkeypatch):
    monkeypatch.setenv("INKVAULT_HOME", str(tmp_path / "vault"))
    from inkvault import embed
    monkeypatch.setattr(embed, "build", lambda: None)  # meaning search needs a model download
    return tmp_path


def claude_dir():
    d = os.path.join(os.environ["CLAUDE_CONFIG_DIR"], "projects", "-home-me-harbor")
    os.makedirs(d, exist_ok=True)
    return d


def write(path, *objs, mode="w", end="\n"):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, mode, encoding="utf-8", newline="") as f:
        f.write("".join(json.dumps(o) + "\n" for o in objs[:-1]) + (json.dumps(objs[-1]) + end if objs else ""))


def turn(type_, uuid, content, ts="2026-10-05T14:00:00Z", **extra):
    return {"type": type_, "uuid": uuid, "sessionId": "sess-1", "timestamp": ts, "cwd": "/home/me/harbor",
            "isSidechain": False, "message": {"role": type_, "content": content}, **extra}


SESSION = [
    {"type": "queue-operation", "operation": "enqueue", "content": "hi"},
    turn("user", "u1", "Add retries to the <b>uploader</b><system-reminder>secret context</system-reminder>"),
    {"type": "attachment", "uuid": "at1", "attachment": {"content": "x" * 500}},
    turn("assistant", "a1", [{"type": "thinking", "thinking": "hmm"}, {"type": "text", "text": "Adding backoff."},
                             {"type": "tool_use", "id": "t1", "name": "Edit", "input": {"file": "up.py"}}],
         ts="2026-10-05T14:00:05Z"),
    turn("user", "u2", [{"type": "tool_result", "tool_use_id": "t1", "content": "API_KEY=sk-123"}]),
    turn("user", "u3", "<command-name>/clear</command-name>"),
    turn("user", "u4", "Caveat: generated by local commands", isMeta=True),
    turn("assistant", "a2", [{"type": "text", "text": "subagent work"}], isSidechain=True),
    turn("assistant", "a3", [{"type": "text", "text": "Done: retries with jitter."}], ts="2026-10-05T14:01:00Z"),
]


def vault_rows(sql):
    from inkvault import paths
    db = sqlite3.connect(paths.vault_db())
    try:
        return db.execute(sql).fetchall()
    finally:
        db.close()


def test_sync_keeps_conversation_lines_only(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    assert sources.sync()
    kept = [json.loads(r)["uuid"] for (r,) in vault_rows("SELECT raw FROM session_lines ORDER BY offset")]
    assert kept == ["u1", "a1", "u3", "u4", "a2", "a3"]  # no queue, attachment or tool result
    assert "sk-123" not in "".join(r for (r,) in vault_rows("SELECT raw FROM session_lines"))


def test_lines_are_stored_verbatim(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    line = '{"type":"user",  "uuid":"u1", "message":{"content":"spacing kept"}}\n'
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(line)
    sources.sync()
    assert vault_rows("SELECT raw FROM session_lines") == [(line.rstrip("\n"),)]


def test_sync_reads_only_what_was_added(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    write(path, *SESSION[:2])
    sources.sync()
    write(path, SESSION[3], mode="a", end="")  # a reply still being written: no newline yet
    sources.sync()
    assert [json.loads(r)["uuid"] for (r,) in vault_rows("SELECT raw FROM session_lines ORDER BY offset")] == ["u1"]
    with open(path, "a", encoding="utf-8") as f:
        f.write("\n")
    write(path, SESSION[-1], mode="a")
    sources.sync()
    sources.sync()  # nothing new: no duplicates
    assert [json.loads(r)["uuid"] for (r,) in vault_rows("SELECT raw FROM session_lines ORDER BY offset")] == \
        ["u1", "a1", "a3"]


def test_a_rewritten_file_is_read_again(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    write(path, *SESSION)
    sources.sync()
    write(path, turn("user", "n1", "a new start"))
    sources.sync()
    assert [json.loads(r)["uuid"] for (r,) in vault_rows("SELECT raw FROM session_lines")] == ["n1"]


def test_a_deleted_session_stays_in_the_vault(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    write(path, *SESSION)
    sources.sync()
    os.remove(path)  # Claude Code's 30-day cleanup
    sources.sync()
    assert vault_rows("SELECT COUNT(*) FROM session_lines") == [(6,)]


def test_subagent_transcripts_are_not_read(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1", "subagents", "agent-1.jsonl"), *SESSION)
    sources.sync()
    assert vault_rows("SELECT COUNT(*) FROM session_lines") == [(0,)]


def test_no_sources_makes_no_vault(home):
    from inkvault import paths, sources
    assert sources.sync() is False
    assert not (home / "vault" / "vault.db").exists() or paths.vault_db().stat().st_size == 0


def test_bad_lines_never_stop_a_sync(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    with open(path, "w", encoding="utf-8") as f:
        f.write("not json\n[1, 2]\n" + json.dumps(SESSION[1]) + "\n")
    assert sources.sync()
    assert vault_rows("SELECT COUNT(*) FROM session_lines") == [(1,)]


def index_messages():
    from inkvault import index, paths
    assert index.build()
    db = sqlite3.connect(paths.search_db())
    try:
        return db.execute("SELECT id, created, conversation_id, conversation_name, role, text, source FROM messages "
                          "ORDER BY created, id").fetchall()
    finally:
        db.close()


def test_claude_code_session_becomes_a_conversation(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    sources.sync()
    rows = index_messages()
    assert [(r[0], r[4], r[5]) for r in rows] == [
        ("claude_code:u1", "USER", "Add retries to the <b>uploader</b>"),
        ("claude_code:a1", "ASSISTANT", "Adding backoff."),
        ("claude_code:a3", "ASSISTANT", "Done: retries with jitter."),
    ]
    assert {r[2] for r in rows} == {"claude_code:sess-1"}
    assert {r[3] for r in rows} == {"Claude Code · harbor: Add retries to the <b>uploader</b>"}
    assert {r[6] for r in rows} == {"claude_code"}


def test_a_session_title_names_the_conversation(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION,
          {"type": "custom-title", "customTitle": "Uploader retries", "sessionId": "sess-1"})
    sources.sync()
    assert {r[3] for r in index_messages()} == {"Claude Code · harbor: Uploader retries"}


def test_a_resumed_session_repeating_lines_indexes_once(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    write(os.path.join(claude_dir(), "sess-2.jsonl"), *SESSION)
    sources.sync()
    assert len(index_messages()) == 3


CODEX_NEW = [
    {"timestamp": "2026-10-06T09:00:00Z", "type": "session_meta",
     "payload": {"id": "cx-1", "timestamp": "2026-10-06T09:00:00Z", "cwd": "C:\\work\\garden"}},
    {"timestamp": "2026-10-06T09:00:01Z", "type": "response_item",
     "payload": {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "<environment_context>\n  <cwd>C:\\work\\garden</cwd>\n</environment_context>"}]}},
    {"timestamp": "2026-10-06T09:00:02Z", "type": "response_item",
     "payload": {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "Fix the planner"}]}},
    {"timestamp": "2026-10-06T09:00:02Z", "type": "event_msg", "payload": {"type": "user_message", "message": "Fix the planner"}},
    {"timestamp": "2026-10-06T09:00:03Z", "type": "response_item",
     "payload": {"type": "function_call_output", "output": "API_KEY=sk-999"}},
    {"timestamp": "2026-10-06T09:00:04Z", "type": "event_msg", "payload": {"type": "token_count", "info": {}}},
    {"timestamp": "2026-10-06T09:00:05Z", "type": "event_msg", "payload": {"type": "agent_message", "message": "Fixed."}},
]


def test_codex_session_uses_what_was_typed_and_said(home):
    from inkvault import sources
    write(os.path.join(os.environ["CODEX_HOME"], "sessions", "2026", "10", "06", "rollout-cx-1.jsonl"), *CODEX_NEW)
    sources.sync()
    assert "sk-999" not in "".join(r for (r,) in vault_rows("SELECT raw FROM session_lines"))
    rows = index_messages()
    assert [(r[4], r[5]) for r in rows] == [("USER", "Fix the planner"), ("ASSISTANT", "Fixed.")]
    assert {(r[2], r[3], r[6]) for r in rows} == {("codex:cx-1", "Codex · garden: Fix the planner", "codex")}


def test_codex_older_format(home):
    from inkvault import sources
    write(os.path.join(os.environ["CODEX_HOME"], "sessions", "rollout-old.jsonl"),
          {"id": "cx-old", "timestamp": "2025-06-01T10:00:00Z", "instructions": ""},
          {"record_type": "state"},
          {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "<user_instructions>\nbe brief\n</user_instructions>"}]},
          {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "Rename the module"}]},
          {"type": "message", "role": "assistant", "content": [{"type": "output_text", "text": "Renamed."}]})
    sources.sync()
    rows = index_messages()
    assert [(r[1], r[4], r[5]) for r in rows] == [("2025-06-01T10:00:00Z", "USER", "Rename the module"),
                                                  ("2025-06-01T10:00:00Z", "ASSISTANT", "Renamed.")]
    assert {r[2] for r in rows} == {"codex:cx-old"}


def test_an_archived_codex_session_is_not_read_twice(home):
    from inkvault import sources
    live = os.path.join(os.environ["CODEX_HOME"], "sessions", "2026", "10", "06", "rollout-cx-1.jsonl")
    write(live, *CODEX_NEW)
    sources.sync()
    archived = os.path.join(os.environ["CODEX_HOME"], "archived_sessions", "rollout-cx-1.jsonl")
    os.makedirs(os.path.dirname(archived))
    os.replace(live, archived)
    sources.sync()
    assert len(index_messages()) == 2


def test_sessions_are_searchable_and_counted(home):
    from inkvault import dashboard, server, sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    sources.sync()
    index_messages()
    hits = server.search_memories("jitter", source="chats", mode="keyword")
    assert "[chats] claude_code:a3" in hits and "Claude Code · harbor" in hits
    assert "Claude Code 3" in server.memory_stats()
    assert "Claude Code · harbor" in server.get_memory("claude_code:a1")
    from inkvault import paths
    db = paths.connect_ro(paths.search_db())
    try:
        assert dashboard.chat_sources(db) == ["Claude Code"]
    finally:
        db.close()


def test_sync_command_syncs_and_indexes(home):
    from inkvault import cli, paths
    assert cli.main(["sync"]) == 1  # nothing on this computer yet
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    assert cli.main(["sync"]) == 0
    assert paths.search_db().exists()


def test_status_lists_synced_sessions(home, capsys):
    from inkvault import cli, sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    sources.sync()
    capsys.readouterr()
    cli.main(["status"])
    assert "Claude Code: 1 sessions (6 lines kept), last sync " in capsys.readouterr().out


def desktop_session(*parts):
    """Where the Claude desktop app keeps an agent-mode session, under the test's data folder."""
    from inkvault import sources
    return os.path.join(str(sources.claude_desktop_roots()[0]), "acct", "org", "local_s1", *parts)


DESKTOP = [dict(o, sessionId="desk-1", uuid=f"d-{o['uuid']}", cwd="/sessions/quiet-amber-otter/lantern")
           for o in SESSION if "uuid" in o] + \
          [{"type": "ai-title", "aiTitle": "Lantern launch plan", "sessionId": "desk-1"}]


def test_claude_desktop_sessions_are_their_own_source(home, capsys):
    from inkvault import cli, sources
    write(desktop_session(".claude", "projects", "-sessions-quiet-amber-otter", "desk-1.jsonl"), *DESKTOP)
    write(desktop_session(".claude", "projects", "-sessions-quiet-amber-otter", "desk-1", "subagents",
                          "agent-1.jsonl"), *DESKTOP)
    write(desktop_session("audit.jsonl"), {"type": "user", "session_id": "desk-1", "message": {"content": "dup"}})
    sources.sync()
    rows = index_messages()
    assert [(r[0], r[4], r[5]) for r in rows] == [
        ("claude_desktop:d-u1", "USER", "Add retries to the <b>uploader</b>"),
        ("claude_desktop:d-a1", "ASSISTANT", "Adding backoff."),
        ("claude_desktop:d-a3", "ASSISTANT", "Done: retries with jitter."),
    ]
    assert {(r[2], r[3], r[6]) for r in rows} == {
        ("claude_desktop:desk-1", "Claude desktop · lantern: Lantern launch plan", "claude_desktop")}
    capsys.readouterr()
    cli.main(["status"])
    assert "Claude desktop: 1 sessions (7 lines kept)" in capsys.readouterr().out


def test_a_desktop_folder_listed_twice_is_read_once(home, monkeypatch, capsys):
    from inkvault import sources
    write(desktop_session(".claude", "projects", "-sessions-x", "desk-1.jsonl"), *DESKTOP)
    root = sources.claude_desktop_roots()[0]
    monkeypatch.setattr(sources, "claude_desktop_roots", lambda: [root, root / "acct" / ".."])  # like %APPDATA%
    sources.sync()
    assert "Claude desktop: 1 sessions, 7 new lines" in capsys.readouterr().out


@pytest.mark.skipif(os.name != "nt", reason="the 260-character limit is Windows'")
def test_a_desktop_session_past_the_windows_path_limit_is_read(home):
    from inkvault import sources
    path = desktop_session(".claude", "projects", "-sessions-" + "deep" * 30, "desk-1.jsonl")
    assert len(path) > 260
    write("\\\\?\\" + path, *DESKTOP)
    sources.sync()
    assert vault_rows("SELECT COUNT(*) FROM session_lines WHERE source='claude_desktop'") == [(7,)]


def test_the_tool_name_is_never_a_project(home):
    from inkvault import dashboard, paths, sources
    for i in range(4):
        write(os.path.join(claude_dir(), f"sess-{i}.jsonl"),
              *[dict(o, sessionId=f"sess-{i}", uuid=f"{o.get('uuid')}-{i}") for o in SESSION])
    sources.sync()
    index_messages()
    db = paths.connect_ro(paths.search_db())
    try:
        data = dashboard.collect(db)
    finally:
        db.close()
    assert not any("Claude" in t or "Code" == t for t in data["themes"])
    assert sum(d["chats"] for d in data["days"].values()) == 12


def test_the_desktop_app_name_is_never_a_project(home):
    from inkvault import dashboard, paths, sources
    for i in range(4):
        write(desktop_session(".claude", "projects", "-sessions-x", f"desk-{i}.jsonl"),
              *[dict(o, sessionId=f"desk-{i}", uuid=f"{o.get('uuid')}-{i}") for o in DESKTOP])
    sources.sync()
    index_messages()
    db = paths.connect_ro(paths.search_db())
    try:
        data = dashboard.collect(db)
        assert dashboard.chat_sources(db) == ["Claude desktop"]
    finally:
        db.close()
    assert not any("Claude" in t or "desktop" in t.lower() for t in data["themes"])


def codex_file(*objs, name="rollout-cx-1.jsonl"):
    write(os.path.join(os.environ["CODEX_HOME"], "sessions", "2026", "10", "06", name), *objs)


def user_item(ts, *texts, extra=()):
    return {"timestamp": ts, "type": "response_item", "payload": {
        "type": "message", "role": "user", "content": [*({"type": "input_text", "text": t} for t in texts), *extra]}}


def reply_item(ts, text):
    return {"timestamp": ts, "type": "response_item",
            "payload": {"type": "message", "role": "assistant", "content": [{"type": "output_text", "text": text}]}}


AGENTS = "# AGENTS.md instructions for C:\\work\\garden\n\n<INSTRUCTIONS>\nUse tabs.\n</INSTRUCTIONS>"


def test_codex_setup_is_not_the_users_words_but_markup_and_answers_are(home):
    from inkvault import sources
    codex_file(CODEX_NEW[0],
               user_item("2026-10-06T09:00:01Z", AGENTS),
               user_item("2026-10-06T09:00:02Z", "<html> please review this"),
               reply_item("2026-10-06T09:00:03Z", "Which file?"),
               user_item("2026-10-06T09:00:04Z",
                         "<send_user_message_question_reply>index.html</send_user_message_question_reply>"),
               user_item("2026-10-06T09:00:05Z", "mentions AGENTS.md instructions in passing"))
    sources.sync()
    rows = index_messages()
    assert [(r[4], r[5]) for r in rows] == [("USER", "<html> please review this"), ("ASSISTANT", "Which file?"),
                                            ("USER", "index.html"),
                                            ("USER", "mentions AGENTS.md instructions in passing")]
    assert {r[3] for r in rows} == {"Codex · garden: <html> please review this"}


def test_images_and_tool_results_are_not_stored(home):
    from inkvault import sources
    image = {"type": "input_image", "image_url": "data:image/png;base64,SECRETPIXELS"}
    codex_file(CODEX_NEW[0], user_item("2026-10-06T09:00:01Z", "what is in this screenshot?", extra=[image]))
    write(os.path.join(claude_dir(), "sess-1.jsonl"),
          turn("user", "u1", [{"type": "text", "text": "and this one?"},
                              {"type": "image", "source": {"type": "base64", "data": "MOREPIXELS"}},
                              {"type": "tool_result", "tool_use_id": "t1", "content": "API_KEY=sk-123"}]))
    sources.sync()
    stored = "".join(r for (r,) in vault_rows("SELECT raw FROM session_lines"))
    assert "SECRETPIXELS" not in stored and "MOREPIXELS" not in stored and "sk-123" not in stored
    assert '{"type": "input_image", "omitted": true}' in stored
    assert sorted(r[5] for r in index_messages()) == ["and this one?", "what is in this screenshot?"]


def test_codex_events_fill_turns_the_response_items_lack(home):
    from inkvault import sources
    codex_file(CODEX_NEW[0],
               user_item("2026-10-06T09:00:01Z", "first ask"), reply_item("2026-10-06T09:00:02Z", "first answer"),
               {"timestamp": "2026-10-06T09:01:00Z", "type": "event_msg",
                "payload": {"type": "user_message", "message": "second ask"}},
               {"timestamp": "2026-10-06T09:01:05Z", "type": "event_msg",
                "payload": {"type": "agent_message", "message": "second answer"}},
               user_item("2026-10-06T09:02:00Z", "third ask"),
               {"timestamp": "2026-10-06T09:02:00Z", "type": "event_msg",
                "payload": {"type": "user_message", "message": "third ask"}})
    sources.sync()
    assert [r[5] for r in index_messages()] == ["first ask", "first answer", "second ask", "second answer",
                                                "third ask"]


def test_a_repeated_prompt_is_kept_each_time(home):
    from inkvault import sources
    codex_file(CODEX_NEW[0], user_item("2026-10-06T09:00:01Z", "run the tests"),
               user_item("2026-10-06T09:05:00Z", "run the tests"))
    sources.sync()
    assert [r[5] for r in index_messages()] == ["run the tests", "run the tests"]


def test_a_copied_codex_session_is_indexed_once(home):
    from inkvault import sources
    codex_file(*CODEX_NEW)
    codex_file(*CODEX_NEW, name="rollout-copy.jsonl")
    sources.sync()
    assert len(index_messages()) == 2


def test_codex_compaction_is_kept_but_not_indexed(home):
    from inkvault import sources
    codex_file(*CODEX_NEW, {"timestamp": "2026-10-06T10:00:00Z", "type": "compacted",
                            "payload": {"message": "Summary of the work so far"}})
    sources.sync()
    assert any("Summary of the work so far" in r for (r,) in vault_rows("SELECT raw FROM session_lines"))
    assert "Summary of the work so far" not in [r[5] for r in index_messages()]


def test_every_codex_setup_shape_is_taken_off_and_what_follows_is_kept(home):
    from inkvault import sources
    codex_file(CODEX_NEW[0],
               user_item("2026-10-06T09:00:01Z", "# AGENTS.md instructions\n\n<INSTRUCTIONS>\nUse tabs.\n</INSTRUCTIONS>"),
               user_item("2026-10-06T09:00:02Z", "# AGENTS.md instructions for C:\\work\n\nNo tags, just rules."),
               user_item("2026-10-06T09:00:03Z", "<recommended_plugins>\n- github\n</recommended_plugins>"),
               user_item("2026-10-06T09:00:04Z", "<external_codex_apps_open_page>\nurl: x\n</external_codex_apps_open_page>"),
               user_item("2026-10-06T09:00:05Z", '<in-app-browser-context url="https://x">\ntab: docs\n'
                                                 '</in-app-browser-context>'),
               user_item("2026-10-06T09:00:05Z", "<guardian_tool_descriptions>[tools]</guardian_tool_descriptions>"),
               user_item("2026-10-06T09:00:05Z", "<task-notification>\ntask done\n</task-notification>"),
               user_item("2026-10-06T09:00:05Z", "<turn_aborted>\ninterrupted\n</turn_aborted>"),
               user_item("2026-10-06T09:00:06Z", AGENTS + "\n<environment_context>\n<cwd>x</cwd>\n</environment_context>\n"
                         "Plan the <b>garden</b> layout"))
    sources.sync()
    rows = index_messages()
    assert [r[5] for r in rows] == ["Plan the <b>garden</b> layout"]
    assert {r[3] for r in rows} == {"Codex · garden: Plan the <b>garden</b> layout"}


@pytest.mark.parametrize("echoed", [True, False])
def test_a_prompt_repeated_in_a_later_turn_is_not_taken_for_its_echo(home, echoed):
    from inkvault import sources
    event = {"type": "event_msg", "payload": {"type": "user_message", "message": "run the tests"}}
    echo = [dict(event, timestamp="2026-10-06T10:01:00Z")] if echoed else []  # the event repeating the item above
    codex_file(CODEX_NEW[0],
               user_item("2026-10-06T10:01:00Z", "run the tests"), *echo,
               reply_item("2026-10-06T10:02:00Z", "All green."),
               dict(event, timestamp="2026-10-06T11:01:00Z"))  # a new turn that only has an event
    sources.sync()
    assert [r[5] for r in index_messages()] == ["run the tests", "All green.", "run the tests"]


def test_a_vault_from_the_earlier_format_is_cleaned_once(home):
    from inkvault import export, sources
    image = {"type": "input_image", "image_url": "data:image/png;base64,OLDPIXELS"}
    live = [CODEX_NEW[0], user_item("2026-10-06T09:00:01Z", "look", extra=[image]),
            {"timestamp": "2026-10-06T10:00:00Z", "type": "compacted", "payload": {"message": "so far"}}]
    codex_file(*live)
    db = export.open_vault()  # what the earlier format stored: images kept, compaction skipped, file fully read
    path = os.path.join(os.environ["CODEX_HOME"], "sessions", "2026", "10", "06", "rollout-cx-1.jsonl")
    lines = open(path, "rb").read().splitlines(keepends=True)
    db.execute("INSERT INTO session_lines VALUES ('codex', 'rollout-cx-1.jsonl', ?, ?)",
               (len(lines[0]), lines[1].decode().rstrip("\n")))
    db.execute("INSERT INTO session_files VALUES ('codex', 'rollout-cx-1.jsonl', ?, ?)",
               (os.path.getsize(path), hashlib.sha1(lines[0]).hexdigest()))
    gone = json.dumps(user_item("2026-01-01T00:00:00Z", "deleted", extra=[image]))  # its file no longer exists
    db.execute("INSERT INTO session_lines VALUES ('codex', 'rollout-gone.jsonl', 0, ?)", (gone,))
    db.commit()
    db.close()
    sources.sync()
    stored = "".join(r for (r,) in vault_rows("SELECT raw FROM session_lines"))
    assert "OLDPIXELS" not in stored
    assert "so far" in stored  # read again from the start: the compaction an earlier format skipped
    assert vault_rows("SELECT value FROM meta WHERE key='session_lines_format'") == [(sources.FORMAT,)]
    assert len(vault_rows("SELECT * FROM session_lines WHERE file='rollout-gone.jsonl'")) == 1


def test_tags_that_are_not_known_setup_are_the_users(home):
    from inkvault import sources
    codex_file(CODEX_NEW[0], user_item("2026-10-06T09:00:01Z", "<my_context>notes I pasted</my_context>"),
               user_item("2026-10-06T09:00:02Z", "<command-name>/review</command-name>"))
    sources.sync()
    assert [r[5] for r in index_messages()] == ["<my_context>notes I pasted</my_context>",
                                                "<command-name>/review</command-name>"]


def test_a_prompt_repeated_without_a_reply_between_is_kept(home):
    from inkvault import sources
    codex_file(CODEX_NEW[0], user_item("2026-10-06T10:01:00Z", "run the tests"),
               {"timestamp": "2026-10-06T11:01:00Z", "type": "event_msg",
                "payload": {"type": "user_message", "message": "run the tests"}})
    sources.sync()
    assert [r[5] for r in index_messages()] == ["run the tests", "run the tests"]


def compaction_with_image(pixels):
    return {"timestamp": "2026-10-06T10:00:00Z", "type": "compacted", "payload": {
        "message": "so far", "replacement_history": [
            {"type": "message", "role": "user", "content": [
                {"type": "input_text", "text": "see data:image/png;base64,TEXTONLY in the docs"},
                {"type": "input_image", "image_url": f"data:image/png;base64,{pixels}"}]}]}}


def test_images_nested_in_compaction_history_are_not_stored(home):
    from inkvault import sources
    codex_file(CODEX_NEW[0], compaction_with_image("NESTEDPIXELS"))
    sources.sync()
    stored = "".join(r for (r,) in vault_rows("SELECT raw FROM session_lines"))
    assert "NESTEDPIXELS" not in stored
    assert "TEXTONLY" in stored and "so far" in stored  # text that merely mentions a data URL stays


def test_a_format_2_vault_is_cleaned_again(home):
    from inkvault import export, sources
    codex_file(CODEX_NEW[0])
    db = export.open_vault()
    db.execute("INSERT INTO session_lines VALUES ('codex', 'rollout-gone.jsonl', 0, ?)",
               (json.dumps(compaction_with_image("FORMAT2PIXELS")),))
    db.execute("INSERT INTO meta VALUES ('session_lines_format', '2')")
    db.commit()
    db.close()
    sources.sync()
    assert "FORMAT2PIXELS" not in "".join(r for (r,) in vault_rows("SELECT raw FROM session_lines"))
    assert vault_rows("SELECT value FROM meta WHERE key='session_lines_format'") == [(sources.FORMAT,)]


SCHEMA = {"type": "object", "properties": {"configPath": {"type": ["string", "null"]}}}


def meta_with_tools():
    return {"timestamp": "2026-10-06T09:00:00Z", "type": "session_meta",
            "payload": {"id": "cx-1", "timestamp": "2026-10-06T09:00:00Z", "cwd": "C:\\work\\garden",
                        "dynamic_tools": [{"name": "open", "inputSchema": SCHEMA}]}}


def test_a_schema_type_list_survives_and_attachments_still_go(home):
    from inkvault import sources
    codex_file(meta_with_tools(), compaction_with_image("SCHEMAPIXELS"), *CODEX_NEW[1:])
    assert sources.sync()
    stored = [json.loads(r) for (r,) in vault_rows("SELECT raw FROM session_lines ORDER BY offset")]
    assert stored[0]["payload"]["dynamic_tools"][0]["inputSchema"] == SCHEMA
    assert "SCHEMAPIXELS" not in json.dumps(stored)
    assert [r[5] for r in index_messages()] == ["Fix the planner", "Fixed."]


def test_a_format_2_vault_with_a_schema_type_list_upgrades(home):
    from inkvault import export, sources
    codex_file(CODEX_NEW[0])
    db = export.open_vault()
    db.executemany("INSERT INTO session_lines VALUES ('codex', 'rollout-gone.jsonl', ?, ?)",
                   [(0, json.dumps(meta_with_tools())), (1, json.dumps(compaction_with_image("OLDSCHEMAPIXELS")))])
    db.execute("INSERT INTO meta VALUES ('session_lines_format', '2')")
    db.commit()
    db.close()
    assert sources.sync()
    stored = [json.loads(r) for (r,) in vault_rows(
        "SELECT raw FROM session_lines WHERE file='rollout-gone.jsonl' ORDER BY offset")]
    assert stored[0]["payload"]["dynamic_tools"][0]["inputSchema"] == SCHEMA
    assert "OLDSCHEMAPIXELS" not in json.dumps(stored)
    assert vault_rows("SELECT value FROM meta WHERE key='session_lines_format'") == [(sources.FORMAT,)]
