"""Claude Code and Codex sessions: what sync keeps, reading only what's new, and the messages index builds."""
import json
import os
import sqlite3

import pytest


@pytest.fixture
def home(tmp_path, monkeypatch):
    monkeypatch.setenv("INKVAULT_HOME", str(tmp_path / "vault"))
    from inkvault import embed
    monkeypatch.setattr(embed, "build", lambda: None)  # meaning search needs a model download
    return tmp_path


def claude_dir():
    d = os.path.join(os.environ["CLAUDE_CONFIG_DIR"], "projects", "-home-me-harbor")
    os.makedirs(d, exist_ok=True)
    return d


def write(path, *objs, mode="w", end="\n"):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, mode, encoding="utf-8", newline="") as f:
        f.write("".join(json.dumps(o) + "\n" for o in objs[:-1]) + (json.dumps(objs[-1]) + end if objs else ""))


def turn(type_, uuid, content, ts="2026-10-05T14:00:00Z", **extra):
    return {"type": type_, "uuid": uuid, "sessionId": "sess-1", "timestamp": ts, "cwd": "/home/me/harbor",
            "isSidechain": False, "message": {"role": type_, "content": content}, **extra}


SESSION = [
    {"type": "queue-operation", "operation": "enqueue", "content": "hi"},
    turn("user", "u1", "Add retries to the <b>uploader</b><system-reminder>secret context</system-reminder>"),
    {"type": "attachment", "uuid": "at1", "attachment": {"content": "x" * 500}},
    turn("assistant", "a1", [{"type": "thinking", "thinking": "hmm"}, {"type": "text", "text": "Adding backoff."},
                             {"type": "tool_use", "id": "t1", "name": "Edit", "input": {"file": "up.py"}}],
         ts="2026-10-05T14:00:05Z"),
    turn("user", "u2", [{"type": "tool_result", "tool_use_id": "t1", "content": "API_KEY=sk-123"}]),
    turn("user", "u3", "<command-name>/clear</command-name>"),
    turn("user", "u4", "Caveat: generated by local commands", isMeta=True),
    turn("assistant", "a2", [{"type": "text", "text": "subagent work"}], isSidechain=True),
    turn("assistant", "a3", [{"type": "text", "text": "Done: retries with jitter."}], ts="2026-10-05T14:01:00Z"),
]


def vault_rows(sql):
    from inkvault import paths
    db = sqlite3.connect(paths.vault_db())
    try:
        return db.execute(sql).fetchall()
    finally:
        db.close()


def test_sync_keeps_conversation_lines_only(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    assert sources.sync()
    kept = [json.loads(r)["uuid"] for (r,) in vault_rows("SELECT raw FROM session_lines ORDER BY offset")]
    assert kept == ["u1", "a1", "u3", "u4", "a2", "a3"]  # no queue, attachment or tool result
    assert "sk-123" not in "".join(r for (r,) in vault_rows("SELECT raw FROM session_lines"))


def test_lines_are_stored_verbatim(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    line = '{"type":"user",  "uuid":"u1", "message":{"content":"spacing kept"}}\n'
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(line)
    sources.sync()
    assert vault_rows("SELECT raw FROM session_lines") == [(line.rstrip("\n"),)]


def test_sync_reads_only_what_was_added(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    write(path, *SESSION[:2])
    sources.sync()
    write(path, SESSION[3], mode="a", end="")  # a reply still being written: no newline yet
    sources.sync()
    assert [json.loads(r)["uuid"] for (r,) in vault_rows("SELECT raw FROM session_lines ORDER BY offset")] == ["u1"]
    with open(path, "a", encoding="utf-8") as f:
        f.write("\n")
    write(path, SESSION[-1], mode="a")
    sources.sync()
    sources.sync()  # nothing new: no duplicates
    assert [json.loads(r)["uuid"] for (r,) in vault_rows("SELECT raw FROM session_lines ORDER BY offset")] == \
        ["u1", "a1", "a3"]


def test_a_rewritten_file_is_read_again(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    write(path, *SESSION)
    sources.sync()
    write(path, turn("user", "n1", "a new start"))
    sources.sync()
    assert [json.loads(r)["uuid"] for (r,) in vault_rows("SELECT raw FROM session_lines")] == ["n1"]


def test_a_deleted_session_stays_in_the_vault(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    write(path, *SESSION)
    sources.sync()
    os.remove(path)  # Claude Code's 30-day cleanup
    sources.sync()
    assert vault_rows("SELECT COUNT(*) FROM session_lines") == [(6,)]


def test_subagent_transcripts_are_not_read(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1", "subagents", "agent-1.jsonl"), *SESSION)
    sources.sync()
    assert vault_rows("SELECT COUNT(*) FROM session_lines") == [(0,)]


def test_no_sources_makes_no_vault(home):
    from inkvault import paths, sources
    assert sources.sync() is False
    assert not (home / "vault" / "vault.db").exists() or paths.vault_db().stat().st_size == 0


def test_bad_lines_never_stop_a_sync(home):
    from inkvault import sources
    path = os.path.join(claude_dir(), "sess-1.jsonl")
    with open(path, "w", encoding="utf-8") as f:
        f.write("not json\n[1, 2]\n" + json.dumps(SESSION[1]) + "\n")
    assert sources.sync()
    assert vault_rows("SELECT COUNT(*) FROM session_lines") == [(1,)]


def index_messages():
    from inkvault import index, paths
    assert index.build()
    db = sqlite3.connect(paths.search_db())
    try:
        return db.execute("SELECT id, created, conversation_id, conversation_name, role, text, source FROM messages "
                          "ORDER BY created, id").fetchall()
    finally:
        db.close()


def test_claude_code_session_becomes_a_conversation(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    sources.sync()
    rows = index_messages()
    assert [(r[0], r[4], r[5]) for r in rows] == [
        ("claude_code:u1", "USER", "Add retries to the <b>uploader</b>"),
        ("claude_code:a1", "ASSISTANT", "Adding backoff."),
        ("claude_code:a3", "ASSISTANT", "Done: retries with jitter."),
    ]
    assert {r[2] for r in rows} == {"claude_code:sess-1"}
    assert {r[3] for r in rows} == {"Claude Code · harbor: Add retries to the <b>uploader</b>"}
    assert {r[6] for r in rows} == {"claude_code"}


def test_a_session_title_names_the_conversation(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION,
          {"type": "custom-title", "customTitle": "Uploader retries", "sessionId": "sess-1"})
    sources.sync()
    assert {r[3] for r in index_messages()} == {"Claude Code · harbor: Uploader retries"}


def test_a_resumed_session_repeating_lines_indexes_once(home):
    from inkvault import sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    write(os.path.join(claude_dir(), "sess-2.jsonl"), *SESSION)
    sources.sync()
    assert len(index_messages()) == 3


CODEX_NEW = [
    {"timestamp": "2026-10-06T09:00:00Z", "type": "session_meta",
     "payload": {"id": "cx-1", "timestamp": "2026-10-06T09:00:00Z", "cwd": "C:\\work\\garden"}},
    {"timestamp": "2026-10-06T09:00:01Z", "type": "response_item",
     "payload": {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "<environment_context>x"}]}},
    {"timestamp": "2026-10-06T09:00:02Z", "type": "response_item",
     "payload": {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "Fix the planner"}]}},
    {"timestamp": "2026-10-06T09:00:02Z", "type": "event_msg", "payload": {"type": "user_message", "message": "Fix the planner"}},
    {"timestamp": "2026-10-06T09:00:03Z", "type": "response_item",
     "payload": {"type": "function_call_output", "output": "API_KEY=sk-999"}},
    {"timestamp": "2026-10-06T09:00:04Z", "type": "event_msg", "payload": {"type": "token_count", "info": {}}},
    {"timestamp": "2026-10-06T09:00:05Z", "type": "event_msg", "payload": {"type": "agent_message", "message": "Fixed."}},
]


def test_codex_session_uses_what_was_typed_and_said(home):
    from inkvault import sources
    write(os.path.join(os.environ["CODEX_HOME"], "sessions", "2026", "10", "06", "rollout-cx-1.jsonl"), *CODEX_NEW)
    sources.sync()
    assert "sk-999" not in "".join(r for (r,) in vault_rows("SELECT raw FROM session_lines"))
    rows = index_messages()
    assert [(r[4], r[5]) for r in rows] == [("USER", "Fix the planner"), ("ASSISTANT", "Fixed.")]
    assert {(r[2], r[3], r[6]) for r in rows} == {("codex:cx-1", "Codex · garden: Fix the planner", "codex")}


def test_codex_older_format(home):
    from inkvault import sources
    write(os.path.join(os.environ["CODEX_HOME"], "sessions", "rollout-old.jsonl"),
          {"id": "cx-old", "timestamp": "2025-06-01T10:00:00Z", "instructions": ""},
          {"record_type": "state"},
          {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "<user_instructions>x"}]},
          {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "Rename the module"}]},
          {"type": "message", "role": "assistant", "content": [{"type": "output_text", "text": "Renamed."}]})
    sources.sync()
    rows = index_messages()
    assert [(r[1], r[4], r[5]) for r in rows] == [("2025-06-01T10:00:00Z", "USER", "Rename the module"),
                                                  ("2025-06-01T10:00:00Z", "ASSISTANT", "Renamed.")]
    assert {r[2] for r in rows} == {"codex:cx-old"}


def test_an_archived_codex_session_is_not_read_twice(home):
    from inkvault import sources
    live = os.path.join(os.environ["CODEX_HOME"], "sessions", "2026", "10", "06", "rollout-cx-1.jsonl")
    write(live, *CODEX_NEW)
    sources.sync()
    archived = os.path.join(os.environ["CODEX_HOME"], "archived_sessions", "rollout-cx-1.jsonl")
    os.makedirs(os.path.dirname(archived))
    os.replace(live, archived)
    sources.sync()
    assert len(index_messages()) == 2


def test_sessions_are_searchable_and_counted(home):
    from inkvault import dashboard, server, sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    sources.sync()
    index_messages()
    hits = server.search_memories("jitter", source="chats", mode="keyword")
    assert "[chats] claude_code:a3" in hits and "Claude Code · harbor" in hits
    assert "Claude Code 3" in server.memory_stats()
    assert "Claude Code · harbor" in server.get_memory("claude_code:a1")
    from inkvault import paths
    db = paths.connect_ro(paths.search_db())
    try:
        assert dashboard.chat_sources(db) == ["Claude Code"]
    finally:
        db.close()


def test_sync_command_syncs_and_indexes(home):
    from inkvault import cli, paths
    assert cli.main(["sync"]) == 1  # nothing on this computer yet
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    assert cli.main(["sync"]) == 0
    assert paths.search_db().exists()


def test_status_lists_synced_sessions(home, capsys):
    from inkvault import cli, sources
    write(os.path.join(claude_dir(), "sess-1.jsonl"), *SESSION)
    sources.sync()
    capsys.readouterr()
    cli.main(["status"])
    assert "Claude Code: 1 sessions (6 lines kept), last sync " in capsys.readouterr().out


def test_the_tool_name_is_never_a_project(home):
    from inkvault import dashboard, paths, sources
    for i in range(4):
        write(os.path.join(claude_dir(), f"sess-{i}.jsonl"),
              *[dict(o, sessionId=f"sess-{i}", uuid=f"{o.get('uuid')}-{i}") for o in SESSION])
    sources.sync()
    index_messages()
    db = paths.connect_ro(paths.search_db())
    try:
        data = dashboard.collect(db)
    finally:
        db.close()
    assert not any("Claude" in t or "Code" == t for t in data["themes"])
    assert sum(d["chats"] for d in data["days"].values()) == 12
